databases:
  - name: securechat-db
    databaseName: securechat
    user: securechatuser
    plan: free
    ipAllowList: []
    region: oregon
  

services:
  # 2. Backend Service (Node.js)
  - name: securechat-backend
    type: web
    plan: free
    runtime: node
    rootDir: ./securechat/fullstack-chat-app/backend
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: MONGO_URI
        fromService:
          name: securechat-db
          type: database
          property: connectionString
      - key: JWT_SECRET
        sync: false # Add this in Render's UI
      - key: CLOUDINARY_CLOUD_NAME
        sync: false # Add this in Render's UI
      - key: CLOUDINARY_API_KEY
        sync: false # Add this in Render's UI
      - key: CLOUDINARY_API_SECRET
        sync: false # Add this in Render's UI
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

  # 3. Frontend Service (React/Vite Static Site)
  - name: securechat-frontend
    type: web
    plan: free
    runtime: static
    rootDir: ./securechat/fullstack-chat-app/frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          name: securechat-backend
          type: web
          property: url 